// capability -> the routes it guards. Add a line here when you add a write route.
export const CAP_ROUTES = {
  'payments.collect': ['POST /payments'],
  'payments.cancel': ['POST /payments/:p/cancel'],
  'payments.reconcile': ['POST /payments/:p/reconcile'],
  'students.write': ['POST /students', 'PATCH /students/:p'],
  'students.withdraw': ['POST /students/:p/withdrawal'],
  'students.withdrawalUndo': ['DELETE /students/:p/withdrawal'],
  'students.concessions': ['PUT /students/:p/concessions'],
  'students.fines': ['PUT /students/:p/fines'],
  'students.facilities': ['PUT /students/:p/facilities'],
  'students.transport': ['PUT /students/:p/transport'],
  'promotions.run': ['POST /promotions'],
  'promotions.undo': ['POST /promotions/undo'],
  'guardians.write': ['POST /students/:p/guardians', 'PATCH /guardians/:p', 'DELETE /guardians/:p', 'PUT /students/:p/subjects'],
  'catalog.write': ['POST /occupations', 'PATCH /occupations/:p', 'DELETE /occupations/:p', 'POST /subjects', 'PATCH /subjects/:p', 'DELETE /subjects/:p'],
  'feeStructure.write': ['PUT /fee-structure'],
  'facilityStructure.write': ['PUT /facilities/structure'],
  'facilities.write': ['POST /facilities', 'PATCH /facilities/:p', 'DELETE /facilities/:p'],
  'stops.write': ['POST /stops', 'PATCH /stops/:p', 'DELETE /stops/:p'],
  'standards.write': ['POST /standards', 'PATCH /standards/:p', 'DELETE /standards/:p', 'POST /sections', 'PATCH /sections/:p', 'DELETE /sections/:p'],
  'feeHeads.write': ['POST /fee-heads', 'PATCH /fee-heads/:p', 'DELETE /fee-heads/:p'],
  'installments.write': ['POST /installments', 'PATCH /installments/:p', 'DELETE /installments/:p'],
  'years.create': ['POST /years'],
  'schools.create': ['POST /schools'],
  'schools.edit': ['PATCH /schools/:p'],
  'users.manage': ['GET /users', 'POST /users', 'PATCH /users/:p'],
  'arrears.carry': ['POST /arrears/carry', 'PATCH /arrears/:p'],
  'deposits.write': ['POST /deposits'],
  'deposits.admin': ['POST /deposits/import', 'POST /deposits/:p/refund'],
  'vouchers.create': ['POST /vouchers'],
  'vouchers.cancel': ['POST /vouchers/:p/cancel'],
  'banks.read': ['GET /banks'],
  'banks.write': ['POST /banks', 'PATCH /banks/:p'],
  'renewals.use': ['GET /transport-renewals', 'POST /transport-renewals'],
  'renewals.admin': ['DELETE /transport-renewals/:p', 'POST /transport-renewals/apply'],
  'documents.use': ['GET /documents/tc/:p/pdf', 'GET /students/:p/fee-certificate', 'GET /students/:p/admission-certificate.pdf',
    'POST /students/:p/admission-certificate/send', 'GET /sections/:p/admission-forms.zip', 'GET /sections/:p/concession-forms.zip', 'GET /students/:p/concession-form'],
  'documents.tcIssue': ['POST /documents/tc'],
  'defaulters.use': ['POST /defaulters/letters', 'GET /defaulter-templates'],
  'defaulters.templates': ['POST /defaulter-templates', 'PUT /defaulter-templates/:p', 'DELETE /defaulter-templates/:p'],
  'sms.use': ['GET /sms-templates', 'POST /sms/send', 'GET /sms/log'],
  'sms.templates': ['POST /sms-templates', 'PATCH /sms-templates/:p', 'DELETE /sms-templates/:p'],
  'email.send': ['POST /email/send'],
  'email.templates': ['GET /email-templates', 'POST /email-templates', 'PATCH /email-templates/:p', 'DELETE /email-templates/:p'],
  'reports.extra': ['classwise', 'studentwise', 'bifurcation', 'transport-bifurcation', 'routes', 'concessions', 'payments-summary', 'siblings',
    'staff-wards', 'minority', 'non-indian', 'occupation', 'subjects', 'fee-head-optin'].map((r) => `GET /reports/${r}`),
  'reports.suggestions': ['GET /reports/siblings/suggestions'],
  'import.run': ['POST /import/students'],
  'audit.read': ['GET /audit'],
  'settings.write': ['PUT /settings/:p'],
}
